name: Dynamic matrix

on: [push, pull_request]

jobs:
  get-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix-linux: ${{ steps.get-matrix-step.outputs.linux }}
      matrix-macos: ${{ steps.get-matrix-step.outputs.macos }}
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: kanaka/get-changed-files@v1
      - id: get-matrix-step
        run: ./get-matrix.py ${{ steps.files.outputs.all }}
  linux:
    needs: get-matrix
    if: ${{ needs.get-matrix.outputs.do-linux == 'true' }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-linux) }}
    steps:
      - uses: actions/checkout@v2
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
  macos:
    needs: get-matrix
    if: ${{ needs.get-matrix.outputs.do-macos == 'true' }}
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-macos) }}
    steps:
      - uses: actions/checkout@v2
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
