name: Dynamic matrix

on: [push, pull_request]

jobs:
  get-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix-linux: ${{ steps.get-matrix-step.outputs.linux }}
      matrix-osx: ${{ steps.get-matrix-step.outputs.osx }}
    steps:
      - uses: actions/checkout@v2
      - id: get-matrix-step
        run: ./get-matrix.py
      - name: show env
        run: set
  linux:
    needs: get-matrix
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-linux) }}
    steps:
      - uses: actions/checkout@v2
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
  macos:
    needs: get-matrix
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix-osx) }}
    steps:
      - uses: actions/checkout@v1
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
