name: Build and Test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        IMPL:
          - IMPL=ada
          - IMPL=basic basic_MODE=cbm NO_SELF_HOST=1  # step4 OOM
          - IMPL=basic basic_MODE=qbasic NO_SELF_HOST=1  # step4 OOM
    steps:
      - uses: actions/checkout@v1
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
  macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        IMPL:
          - IMPL=swift5 NO_DOCKER=1
    steps:
      - uses: actions/checkout@v1
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
          
