name: Build and Test (other)

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        IMPL:
          - IMPL=foo
          - IMPL=bar basic_MODE=cbm NO_SELF_HOST=1  # step4 OOM
          - IMPL=bar basic_MODE=qbasic NO_SELF_HOST=1  # step4 OOM
    steps:
      - uses: actions/checkout@v1
      - name: IMPL testing
        run: |
          echo "matrix.IMPL: ${{ matrix.IMPL }}"
